services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        volumes:
            - ./app:/var/www/html/app
            - ./routes:/var/www/html/routes
            - ./resources:/var/www/html/resources
            # Hindari mount root Laravel langsung

